services:
  # api:
  #   image: "leonarolivei/politks-api:1.0.0-SNAPSHOT"
  #   build:
  #     context: .
  #   container_name: politks-api
  #   depends_on:
  #     - db
  #   environment:
  #     - DB_USERNAME=postgres
  #     - DB_PASSWORD=postgres
  #     - DB_URL=jdbc:postgresql://db:5432/politks
  #     - HIBERNATE_GENERATION=update
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - politks-network

  db:
    image: "postgres:latest"
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=politks
    ports:
      - "5432:5432"
    networks:
      - politks-network

networks:
  politks-network:
    driver: bridge
